# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

from enum import Enum, auto
import sys
import termios
import tty
import select
import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    #bi_so100_follower,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    #so100_follower,
    so101_follower,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_devices
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data



class ControlMode(Enum):
    POLICY = auto()
    PAUSED_FOR_ALIGNMENT = auto()
    TELEOP_INTERVENTION = auto()
    PAUSED_AFTER_INTERVENTION = auto()


class NonBlockingKeyboard:
    """Non-blocking single-key reader for Linux terminal."""

    def __init__(self):
        self.fd = sys.stdin.fileno()
        self.old_settings = None

    def __enter__(self):
        self.old_settings = termios.tcgetattr(self.fd)
        tty.setcbreak(self.fd)
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if self.old_settings is not None:
            termios.tcsetattr(self.fd, termios.TCSADRAIN, self.old_settings)

    def get_key(self) -> str | None:
        dr, _, _ = select.select([sys.stdin], [], [], 0)
        if dr:
            return sys.stdin.read(1)
        return None

@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


class RelativeLeaderActionMapper:
    """Convert absolute leader joint positions into follower-relative joint targets."""

    def __init__(self, gripper_mode: str = "absolute"):
        self.leader_ref = None
        self.follower_ref = None
        self.gripper_mode = gripper_mode

    def reset(
        self,
        leader_action: dict[str, float],
        follower_pos: dict[str, float],
    ) -> None:
        self.leader_ref = {key: float(value) for key, value in leader_action.items()}
        self.follower_ref = {key: float(value) for key, value in follower_pos.items()}

    def __call__(
        self,
        leader_action: dict[str, float],
        motor_names: list[str],
    ) -> dict[str, float]:
        if self.leader_ref is None or self.follower_ref is None:
            raise RuntimeError("RelativeLeaderActionMapper must be reset before use.")

        target = {}

        for name in motor_names:
            key = f"{name}.pos"

            if name == "gripper" and self.gripper_mode == "absolute":
                target[key] = float(leader_action[key])
                continue

            leader_delta = float(leader_action[key]) - float(self.leader_ref[key])
            target[key] = float(self.follower_ref[key]) + leader_delta

        return target

def compute_leader_follower_diffs(
    leader_action: dict[str, float],
    follower_ref: dict[str, float],
    motor_names: list[str],
    ignore_gripper_for_check: bool = True,
) -> tuple[dict[str, float], float]:
    """Compute joint-wise leader - follower differences.

    Returns:
        diffs:
            key -> leader_pos - follower_pos
        max_abs_diff:
            maximum absolute difference, optionally excluding gripper
    """
    diffs = {}
    abs_diffs_for_check = []

    for name in motor_names:
        key = f"{name}.pos"

        if key not in leader_action or key not in follower_ref:
            continue

        diff = float(leader_action[key]) - float(follower_ref[key])
        diffs[key] = diff

        if ignore_gripper_for_check and name == "gripper":
            continue

        abs_diffs_for_check.append(abs(diff))

    max_abs_diff = max(abs_diffs_for_check) if abs_diffs_for_check else float("inf")

    return diffs, max_abs_diff


def render_leader_follower_alignment(
    teleop,
    follower_ref: dict[str, float],
    motor_names: list[str],
    threshold_deg: float = 10.0,
) -> str:
    """Return a multi-line alignment guide string.

    This does not print by itself.
    It is intended to be rendered repeatedly by overwriting terminal lines.
    """
    leader_action = teleop.get_action()

    diffs, max_abs_diff = compute_leader_follower_diffs(
        leader_action=leader_action,
        follower_ref=follower_ref,
        motor_names=motor_names,
        ignore_gripper_for_check=True,
    )

    lines = []
    lines.append("[Leader-Follower alignment guide]")
    lines.append(f"max_abs_diff(except gripper): {max_abs_diff:6.2f} deg   threshold: {threshold_deg:6.2f} deg")
    lines.append("Press 's' to start intervention. Press 'r' to resume policy is disabled here.")
    lines.append("")

    for name in motor_names:
        key = f"{name}.pos"

        if key not in leader_action or key not in follower_ref:
            lines.append(f"{key:18s}: missing")
            continue

        leader_pos = float(leader_action[key])
        follower_pos = float(follower_ref[key])
        diff = leader_pos - follower_pos

        if name == "gripper":
            mark = "--"
        else:
            mark = "OK" if abs(diff) <= threshold_deg else "!!"

        # 簡易バー表示：差分の方向と大きさを視覚的に見る
        bar_width = 20
        clipped = max(-threshold_deg, min(threshold_deg, diff))
        center = bar_width
        pos = int(center + (clipped / threshold_deg) * bar_width) if threshold_deg > 0 else center

        bar_chars = [" "] * (bar_width * 2 + 1)
        bar_chars[center] = "|"
        if 0 <= pos < len(bar_chars):
            bar_chars[pos] = "*"

        bar = "".join(bar_chars)

        lines.append(
            f"{key:18s} "
            f"L={leader_pos:8.2f} "
            f"F={follower_pos:8.2f} "
            f"d={diff:8.2f}  {mark}  [{bar}]"
        )

    if max_abs_diff <= threshold_deg:
        lines.append("")
        lines.append("Alignment looks good.")
    else:
        lines.append("")
        lines.append("Align leader closer to follower if possible, but 's' will still start intervention.")

    return "\n".join(lines)

def overwrite_terminal_block(text: str, previous_num_lines: int = 0) -> int:
    """Overwrite a multi-line terminal block.

    Returns:
        number of rendered lines
    """
    lines = text.splitlines()
    num_lines = len(lines)

    if previous_num_lines > 0:
        # Move cursor up to the beginning of previous block
        sys.stdout.write(f"\033[{previous_num_lines}F")
        # Clear from cursor to end of screen
        sys.stdout.write("\033[J")

    sys.stdout.write(text + "\n")
    sys.stdout.flush()

    return num_lines

def clear_terminal_block(previous_num_lines: int) -> int:
    if previous_num_lines > 0:
        sys.stdout.write(f"\033[{previous_num_lines}F")
        sys.stdout.write("\033[J")
        sys.stdout.flush()
    return 0


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""

@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    if policy is None:
        raise ValueError("This HIL pause prototype currently expects a policy.")

    if preprocessor is None or postprocessor is None:
        raise ValueError("This HIL pause prototype requires policy preprocessor and postprocessor.")

    # Reset policy and processors at episode start.
    policy.reset()
    preprocessor.reset()
    postprocessor.reset()

    mode = ControlMode.POLICY
    relative_mapper = RelativeLeaderActionMapper(gripper_mode="absolute")

    #介入時の初期に破棄するステップ数
    warmup_steps = 5
    intervention_step = 0

    # 差分制御アラインメント設定
    alignment_threshold_deg = 10.0
    alignment_render_every_steps = 3  # update every control loop
    alignment_render_lines = 0
    step_idx = 0

    motor_names = list(robot.bus.motors.keys())
    print("motor_names:", motor_names)

    # last_commanded_action:
    #   The last action in robot/dataset action scale, before robot_action_processor.
    #   Pause mode sends this repeatedly to hold the previous target.
    last_commanded_action: RobotAction | None = None
    hold_action: RobotAction | None = None

    print("HIL policy-pause record_loop started")
    print("Controls:")
    print("  p: POLICY -> PAUSE")
    print("  s: PAUSE -> INTERVENTION")
    print("  e: INTERVENTION -> PAUSE")
    print("  r: PAUSE -> POLICY")
    print("  q: exit current episode")

    timestamp = 0
    start_episode_t = time.perf_counter()

    with NonBlockingKeyboard() as keyboard:
        while timestamp < control_time_s:
            start_loop_t = time.perf_counter()

            if events["exit_early"]:
                events["exit_early"] = False
                break

            key = keyboard.get_key()

            if key == "q":
                print("Quit requested.")
                break

            if mode == ControlMode.POLICY:
                if key == "p":
                    if last_commanded_action is None:
                        print("Pause requested, but last_commanded_action is None. Ignoring.")
                    else:
                        hold_action = last_commanded_action.copy()
                        mode = ControlMode.PAUSED_FOR_ALIGNMENT
                        print("POLICY -> PAUSED_FOR_ALIGNMENT")
                        print("Follower is holding last commanded action.")
                        print("Manually align leader near follower, then press 's'.")

            elif mode == ControlMode.PAUSED_FOR_ALIGNMENT:
                if key == "s":
                    if teleop is None:
                        print("Cannot start teleop intervention: teleop is None.")

                    elif hold_action is None:
                        print("Cannot start teleop intervention: hold_action is None.")

                    else:
                        alignment_render_lines = clear_terminal_block(alignment_render_lines)

                        leader_action = teleop.get_action()

                        diffs, max_diff = compute_leader_follower_diffs(
                            leader_action=leader_action,
                            follower_ref=hold_action,
                            motor_names=motor_names,
                            ignore_gripper_for_check=True,
                        )

                        if max_diff > alignment_threshold_deg:
                            print(
                                f"[WARN] Starting teleop intervention with leader/follower mismatch: "
                                f"max_diff={max_diff:.2f} deg > threshold={alignment_threshold_deg:.2f} deg"
                            )

                        leader_ref = leader_action
                        follower_ref = hold_action.copy()

                        relative_mapper.reset(
                            leader_action=leader_ref,
                            follower_pos=follower_ref,
                        )

                        intervention_step = 0
                        mode = ControlMode.TELEOP_INTERVENTION

                        print("PAUSED_FOR_ALIGNMENT -> TELEOP_INTERVENTION")
                        print("Relative mapper reset.")

            elif mode == ControlMode.TELEOP_INTERVENTION:
                if key == "e":
                    hold_action = last_commanded_action.copy()
                    intervention_step = 0

                    mode = ControlMode.PAUSED_AFTER_INTERVENTION
                    print("TELEOP_INTERVENTION -> PAUSED_AFTER_INTERVENTION")
                    print("Follower is holding final intervention target.")
                    print("Press 'r' to resume policy.")

            elif mode == ControlMode.PAUSED_AFTER_INTERVENTION:
                if key == "r":
                    mode = ControlMode.POLICY
                    policy.reset()
                    preprocessor.reset()
                    postprocessor.reset()
                    print("PAUSED_AFTER_INTERVENTION -> POLICY")
                    print("Policy and processors reset.")

            if (
                mode == ControlMode.PAUSED_FOR_ALIGNMENT
                and hold_action is not None
                and teleop is not None
                and step_idx % alignment_render_every_steps == 0
            ):
                guide_text = render_leader_follower_alignment(
                    teleop=teleop,
                    follower_ref=hold_action,
                    motor_names=motor_names,
                    threshold_deg=alignment_threshold_deg,
                )
                alignment_render_lines = overwrite_terminal_block(
                    guide_text,
                    previous_num_lines=alignment_render_lines,
                )


            # --- Observation path: keep official record_loop behavior ---
            obs = robot.get_observation()
            obs_processed = robot_observation_processor(obs)

            if policy is not None or dataset is not None:
                observation_frame = build_dataset_frame(
                    dataset.features,
                    obs_processed,
                    prefix=OBS_STR,
                )

            # --- Action selection with HIL mode ---
            if mode == ControlMode.POLICY:
                action_values = predict_action(
                    observation=observation_frame,
                    policy=policy,
                    device=get_safe_torch_device(policy.config.device),
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    use_amp=policy.config.use_amp,
                    task=single_task,
                    robot_type=robot.robot_type,
                )

                action_values = make_robot_action(
                    action_values,
                    dataset.features,
                )

            elif mode == ControlMode.PAUSED_FOR_ALIGNMENT:
                if hold_action is None:
                    raise RuntimeError("hold_action is None in PAUSED_FOR_ALIGNMENT mode.")
                action_values = hold_action

            elif mode == ControlMode.TELEOP_INTERVENTION:
                if teleop is None:
                    raise RuntimeError("teleop is None in TELEOP_INTERVENTION mode.")

                leader_action = teleop.get_action()

                action_values = relative_mapper(
                    leader_action=leader_action,
                    motor_names=motor_names,
                )

            elif mode == ControlMode.PAUSED_AFTER_INTERVENTION:
                if hold_action is None:
                    raise RuntimeError("hold_action is None in PAUSED_AFTER_INTERVENTION mode.")
                action_values = hold_action

            else:
                raise RuntimeError(f"Unknown mode: {mode}")

            # --- Robot action path: keep official record_loop behavior ---
            robot_action_to_send = robot_action_processor((action_values, obs))
            _sent_action = robot.send_action(robot_action_to_send)

            # Save last action BEFORE any future pause transition.
            # This is the target that will be held during PAUSE.
            last_commanded_action = action_values.copy()

            # --- Dataset writing ---
            # For the first prototype, save frames as usual.
            # Later, we will add control_mode / valid_for_dagger masks.
            # 介入区間のみ保存する方式に変更する
            should_save_frame = (
                dataset is not None
                and mode == ControlMode.TELEOP_INTERVENTION
                and intervention_step >= warmup_steps
            )

            # 介入区間の場合保存する
            if should_save_frame:
                action_frame = build_dataset_frame(
                    dataset.features,
                    action_values,
                    prefix=ACTION,
                )
                frame = {
                    **observation_frame,
                    **action_frame,
                    "task": single_task,
                }
                dataset.add_frame(frame)

            if display_data:
                log_rerun_data(
                    observation=obs_processed,
                    action=action_values,
                )
            
            if mode == ControlMode.TELEOP_INTERVENTION:
                intervention_step += 1
            
            step_idx += 1

            dt_s = time.perf_counter() - start_loop_t
            busy_wait(1 / fps - dt_s)

            timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
    preprocessor = None
    postprocessor = None
    if cfg.policy is not None:
        preprocessor, postprocessor = make_pre_post_processors(
            policy_cfg=cfg.policy,
            pretrained_path=cfg.policy.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": cfg.policy.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                teleop=teleop,
                policy=policy,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue

            dataset.save_episode()
            recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_devices()
    record()


if __name__ == "__main__":
    main()
